services:
  playwright-api:
    platform: linux/amd64   # <-- add this
    build: .
    container_name: playwright-api
    shm_size: '2gb'
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - my-project

networks:
  my-project:
