services:
  playwright-api:
    platform: linux/arm64
    build: .
    container_name: playwright-api
    shm_size: '2gb'
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - web_network

networks:
  web_network:
    external: true
    name: my-project_web_network